/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controller.AgendaController;
import Model.DAO.AgendamentoDAO;
import Model.DAO.ClienteDAO;
import Model.DAO.ServicoDAO;
import Model.bean.Agendamento;
import Model.bean.Cliente;
import Model.bean.Servico;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author Ana
 */
public class Agenda extends javax.swing.JFrame {
Conexao conecta = new Conexao();
     Connection con = Conexao.getConnection();
     PreparedStatement stmt = null;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        setTitle("Salão de Beleza - Agenda");
        Connection con = Conexao.getConnection();
        ClienteDAO dao = new ClienteDAO(con);
        ServicoDAO sdao = new ServicoDAO(con);
        ServicoDAO cdao = new ServicoDAO(con);
        
        for(Cliente a: dao.read()){
            CaixaNome.addItem(a);
        }
        for(Servico s: sdao.read()){
            CaixaServico.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotaoCadastrar = new javax.swing.JButton();
        CaixaNome = new javax.swing.JComboBox<>();
        CaixaData = new javax.swing.JFormattedTextField();
        CaixaServico = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CaixaHora = new javax.swing.JTextField();
        CaixaValor = new javax.swing.JComboBox<>();
        BotaoCadastrar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome**");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 71, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Valor R$");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 151, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Serviço");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 111, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Horário");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 198, 53, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 236, 47, -1));

        BotaoCadastrar.setBackground(new java.awt.Color(255, 51, 51));
        BotaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCadastrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\HDD\\Desktop\\SalaoDeBeleza\\src\\Imagens\\Add-icon.png")); // NOI18N
        BotaoCadastrar.setText("Agendar");
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 130, 30));

        CaixaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaNomeActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 67, 226, -1));
        getContentPane().add(CaixaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 227, -1));

        getContentPane().add(CaixaServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 226, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Agenda");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));
        getContentPane().add(CaixaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 227, -1));

        CaixaValor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10,00", "15,00", "20,00", "80,00", "90,00", "140,00" }));
        CaixaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaValorActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 226, -1));

        BotaoCadastrar1.setBackground(new java.awt.Color(255, 51, 51));
        BotaoCadastrar1.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCadastrar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HDD\\Desktop\\SalaoDeBeleza\\src\\Imagens\\Trash-icon.png")); // NOI18N
        BotaoCadastrar1.setText("Excluir");
        BotaoCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCadastrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 130, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HDD\\Desktop\\unnamed.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 330));

        jMenu1.setText("Agendamento");

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HDD\\Desktop\\SalaoDeBeleza\\src\\Imagens\\calendar-icon.png")); // NOI18N
        jMenuItem1.setText("Visualizar Agendamentos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
       String nome_cliente =  CaixaNome.getSelectedItem().toString();
       String nome_servico =  CaixaServico.getSelectedItem().toString();
       String valor = CaixaValor.getSelectedItem().toString();
       String data = CaixaData.getText();
       String hora = CaixaHora.getText();
        
        Agendamento agendamento = new Agendamento();
        
        Connection con = Conexao.getConnection();
        AgendamentoDAO agendamentoDao = new AgendamentoDAO(con);
        
        agendamento.setNome_Cliente(nome_cliente);
        agendamento.setNome_Servico(nome_servico);     
        agendamento.setValor(valor);  
        agendamento.setData(data); 
        agendamento.setHora(hora); 
        agendamentoDao.create(agendamento);
        
        CaixaNome.setSelectedItem("");
        CaixaServico.setSelectedItem("");
        CaixaValor.setSelectedItem("");
        CaixaData.setText("");
        CaixaHora.setText("");
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void CaixaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaNomeActionPerformed

    private void CaixaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaValorActionPerformed

    private void BotaoCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCadastrar1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         VisualizaAgendamentos visuAgenda = new VisualizaAgendamentos();
         visuAgenda.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoCadastrar1;
    private javax.swing.JFormattedTextField CaixaData;
    private javax.swing.JTextField CaixaHora;
    private javax.swing.JComboBox<Object> CaixaNome;
    private javax.swing.JComboBox<Object> CaixaServico;
    private javax.swing.JComboBox<String> CaixaValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    
}
