/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controller.LoginController;
import Model.bean.Usuario;
import Model.DAO.UsuarioDAO;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Ana
 */
public class Login extends javax.swing.JFrame {

    
    Conexao conn = new Conexao();
    private final LoginController controller;
    

    /**
     * Creates new form Login
     */
    public Login() throws SQLException {
        initComponents();
        setTitle("Salão de Beleza - LOGIN");
        controller = new LoginController(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PalavraLogin = new javax.swing.JLabel();
        PalavraUsuario = new javax.swing.JLabel();
        PalavraSenha = new javax.swing.JLabel();
        CaixaUsuario = new javax.swing.JTextField();
        CaixaSenha = new javax.swing.JPasswordField();
        BotaoEntrar = new javax.swing.JButton();
        ImagemBranca = new javax.swing.JLabel();
        ImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(60, 64));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PalavraLogin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        PalavraLogin.setText("LOGIN");
        getContentPane().add(PalavraLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        PalavraUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PalavraUsuario.setText("USUÁRIO");
        getContentPane().add(PalavraUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        PalavraSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PalavraSenha.setText("SENHA");
        getContentPane().add(PalavraSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        CaixaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 190, -1));

        CaixaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 190, -1));

        BotaoEntrar.setBackground(new java.awt.Color(255, 51, 51));
        BotaoEntrar.setText("Entrar");
        BotaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        ImagemBranca.setBackground(new java.awt.Color(255, 51, 102));
        ImagemBranca.setForeground(new java.awt.Color(204, 255, 204));
        ImagemBranca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ImagemBranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/download (1).png"))); // NOI18N
        getContentPane().add(ImagemBranca, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        ImagemFundo.setForeground(new java.awt.Color(204, 255, 153));
        ImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/papel-de-parede-tematico-barbearia-salao-cabeleireiro.jpg"))); // NOI18N
        getContentPane().add(ImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CaixaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaUsuarioActionPerformed

    private void BotaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEntrarActionPerformed
        
        try {
            /*String login = CaixaUsuario.getText();
            String senha = CaixaSenha.getText();
            
            Usuario usuario = new Usuario(login,senha);
            
            Connection con = Conexao.getConnection();
            UsuarioDAO usuarioDao = new UsuarioDAO(con);
            
            usuario.setLogin(CaixaUsuario.getText());
            usuario.setSenha(CaixaSenha.getText());
            usuarioDao.create(usuario);
            
            CaixaUsuario.setText("");
            CaixaSenha.setText("");*/
            if(controller.autenticar())
                this.dispose();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoEntrarActionPerformed

    private void CaixaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JPasswordField getCaixaSenha() {
        return CaixaSenha;
    }

    public void setCaixaSenha(JPasswordField CaixaSenha) {
        this.CaixaSenha = CaixaSenha;
    }

    public JTextField getCaixaUsuario() {
        return CaixaUsuario;
    }

    public void setCaixaUsuario(JTextField CaixaUsuario) {
        this.CaixaUsuario = CaixaUsuario;
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoEntrar;
    private javax.swing.JPasswordField CaixaSenha;
    private javax.swing.JTextField CaixaUsuario;
    private javax.swing.JLabel ImagemBranca;
    private javax.swing.JLabel ImagemFundo;
    private javax.swing.JLabel PalavraLogin;
    private javax.swing.JLabel PalavraSenha;
    private javax.swing.JLabel PalavraUsuario;
    // End of variables declaration//GEN-END:variables

 

    
    
    
}
