/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Ana
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setTitle("Salão de Beleza");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        CadastroCliente = new javax.swing.JMenuItem();
        CadastroServico = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        MenuServicos = new javax.swing.JMenu();
        VisualizarServicos = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenu();
        ConsultaCliente = new javax.swing.JMenuItem();
        MenuAgendamentos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 64));
        setMinimumSize(new java.awt.Dimension(60, 64));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/jacques-janine-salao-beleza-orlando.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1100, 1016));
        jLabel1.setMinimumSize(new java.awt.Dimension(1100, 1016));

        MenuCadastro.setText("Cadastro");

        CadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/User-icon (1).png"))); // NOI18N
        CadastroCliente.setText("Cadastro de Cliente");
        CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteActionPerformed(evt);
            }
        });
        MenuCadastro.add(CadastroCliente);

        CadastroServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Hair-Dryer-icon.png"))); // NOI18N
        CadastroServico.setText("Cadastro de Serviço");
        CadastroServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroServicoActionPerformed(evt);
            }
        });
        MenuCadastro.add(CadastroServico);

        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel-icon.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        MenuCadastro.add(Sair);

        jMenuBar1.add(MenuCadastro);

        MenuServicos.setText("Serviços");

        VisualizarServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Magnifi-Glass-2-2-icon.png"))); // NOI18N
        VisualizarServicos.setText("Visualizar Serviços");
        VisualizarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarServicosActionPerformed(evt);
            }
        });
        MenuServicos.add(VisualizarServicos);

        jMenuBar1.add(MenuServicos);

        Clientes.setText("Clientes");

        ConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/users-icon.png"))); // NOI18N
        ConsultaCliente.setText("Gerenciar Clientes");
        ConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaClienteActionPerformed(evt);
            }
        });
        Clientes.add(ConsultaCliente);

        jMenuBar1.add(Clientes);

        MenuAgendamentos.setText("Agenda");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar-icon.png"))); // NOI18N
        jMenuItem1.setText("Agendar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuAgendamentos.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Address-Book-2-icon.png"))); // NOI18N
        jMenuItem2.setText("Visualizar Agendamentos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuAgendamentos.add(jMenuItem2);

        jMenuBar1.add(MenuAgendamentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteActionPerformed
        CadastroCliente cadCliente = new CadastroCliente();
        cadCliente.setVisible(true);
    }//GEN-LAST:event_CadastroClienteActionPerformed

    private void CadastroServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroServicoActionPerformed
        CadastroServico cadServ = new CadastroServico();
        cadServ.setVisible(true);
    }//GEN-LAST:event_CadastroServicoActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
      this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void ConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaClienteActionPerformed
        Clientes clientes = new Clientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_ConsultaClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Agenda agenda = new Agenda();
        agenda.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        VisualizaAgendamentos visuAgenda = new VisualizaAgendamentos();
        visuAgenda.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void VisualizarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarServicosActionPerformed
        Servicos servicos = new Servicos();
        servicos.setVisible(true);
    }//GEN-LAST:event_VisualizarServicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroCliente;
    private javax.swing.JMenuItem CadastroServico;
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenuItem ConsultaCliente;
    private javax.swing.JMenu MenuAgendamentos;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuServicos;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem VisualizarServicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
